CREATE TABLE usuarios (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  password VARCHAR(255)
);

CREATE TABLE estados_tarea (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255)
);
